const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('touch', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (partial) => ipcRenderer.invoke('settings:set', partial),
  getGameUrl: () => ipcRenderer.invoke('game:url'),
  getGamePreloadUrl: () => ipcRenderer.invoke('game:preload-path'),
  getPatchStatus: () => ipcRenderer.invoke('patch:status'),
  retryPatch: () => ipcRenderer.invoke('patch:retry'),
  getAppVersion: () => ipcRenderer.invoke('app:version'),
  accountsList: () => ipcRenderer.invoke('accounts:list'),
  accountsAdd: (name) => ipcRenderer.invoke('accounts:add', name),
  accountsRename: (id, name) => ipcRenderer.invoke('accounts:rename', id, name),
  accountsRemove: (id) => ipcRenderer.invoke('accounts:remove', id),
  accountsReorder: (ids) => ipcRenderer.invoke('accounts:reorder', ids),
  broadcastKey: (wcIds, key) => ipcRenderer.invoke('broadcast:key', wcIds, key),
  prepareSession: (partition) => ipcRenderer.invoke('session:prepare', partition),
  windowMinimize: () => ipcRenderer.send('window:minimize'),
  windowToggleMaximize: () => ipcRenderer.send('window:toggle-maximize'),
  windowClose: () => ipcRenderer.send('window:close'),
  windowToggleFullscreen: () => ipcRenderer.send('window:toggle-fullscreen'),
  securityInfo: () => ipcRenderer.invoke('security:info'),
  securityFlag: (reason, meta) => ipcRenderer.invoke('security:flag', reason, meta),
  securityBan: (machineId, reason) => ipcRenderer.invoke('security:ban', machineId, reason),
  securityUnban: (machineId) => ipcRenderer.invoke('security:unban', machineId),
  signalAttention: () => ipcRenderer.send('window:attention'),
  installUpdate: () => ipcRenderer.invoke('updater:install'),
  onUpdaterStatus: (cb) => ipcRenderer.on('updater:status', (_e, s) => cb(s)),
});
