const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('touch', {
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (partial) => ipcRenderer.invoke('settings:set', partial),
  getGameUrl: () => ipcRenderer.invoke('game:url'),
  getGamePreloadUrl: () => ipcRenderer.invoke('game:preload-path'),
  getPatchStatus: () => ipcRenderer.invoke('patch:status'),
  retryPatch: () => ipcRenderer.invoke('patch:retry'),
  getAppVersion: () => ipcRenderer.invoke('app:version'),
  openExternal: (url) => ipcRenderer.invoke('app:open-external', url),
  logDebug: (tag, data) => ipcRenderer.send('debug:log', tag, data),
  accountsList: () => ipcRenderer.invoke('accounts:list'),
  accountsAdd: (name) => ipcRenderer.invoke('accounts:add', name),
  accountsRename: (id, name) => ipcRenderer.invoke('accounts:rename', id, name),
  accountsRemove: (id) => ipcRenderer.invoke('accounts:remove', id),
  accountsReorder: (ids) => ipcRenderer.invoke('accounts:reorder', ids),
  broadcastKey: (wcIds, key) => ipcRenderer.invoke('broadcast:key', wcIds, key),
  prepareSession: (partition) => ipcRenderer.invoke('session:prepare', partition),
  previewSize: (w, h) => ipcRenderer.send('window:preview-size', w, h),
  windowMinimize: () => ipcRenderer.send('window:minimize'),
  windowToggleMaximize: () => ipcRenderer.send('window:toggle-maximize'),
  windowClose: () => ipcRenderer.send('window:close'),
  windowToggleFullscreen: () => ipcRenderer.send('window:toggle-fullscreen'),
  signalAttention: () => ipcRenderer.send('window:attention'),
  installUpdate: () => ipcRenderer.invoke('updater:install'),
  onUpdaterStatus: (cb) => ipcRenderer.on('updater:status', (_e, s) => cb(s)),
});
